name: Publish Package

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scm
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/gallium'      

      - name: Show project version
        run: |
          echo "TEST"

